[platformio]
name = Project-Firmware
description = Short description of the firmware
default_envs = target_name ; set to the primary or production target
extra_configs =
  hardware/**/*.ini

[default]
build_flags =
  ${debug.build_flags}
lib_deps =
  ${debug.lib_deps}

[debug]
build_flags =
  -D DEBUG_ENABLE
lib_deps =
  https://github.com/LeeorNahum/SimpleDebug.git#main
