; hardware/target_name/target_name.ini
[env:target_name]
platform = https://github.com/example/platform-board-package.git#main
board = <pio-board-id>
framework = arduino
monitor_speed = 115200
build_flags =
  ${default.build_flags}
  -include hardware/target_name/target_name.h
lib_deps =
  ${default.lib_deps}
  https://github.com/example/Driver_Library.git#main
